class Querys_perneria:

    #Sentencias a la base de datos
    
    QUERY_ALL_PERNERIA = "SELECT ID_PERNO, OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
                        CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
                        FROM railway.control_perneria;"
    
    QUERY_PERNERIA_X_SNF = "SELECT ID_PERNO, OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
                    CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
                    FROM railway.control_perneria "
    
    QUERY_PERNERIA_PENDIENTES = "SELECT ID_PERNO, OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
FROM railway.control_perneria  WHERE DIFERENCIA != 0"

    QUERY_PERNERIA_COMPLETAS = "SELECT ID_PERNO, OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
FROM railway.control_perneria  WHERE DIFERENCIA = 0"
                    
    