class Querys_equipos:

    #Sentencias a la base de datos
    
    QUERY_ALL_EQUIPOS = "SELECT CAT_FILA, CAT_DISCIPLINA, CAT_MATL_TYPE, CAT_TAG_NUMBER, CAT_DESCRIPCION, CAT_CWP, CAT_CWP_DESCRIPCION, \
CAT_CONTRATO, CAT_DESTINO, CAT_ESTADO, REQ_LOG, REQ_REQ_NUMERO, REQ_DESCRIPCION_SUPLEMENTO, REQ_NUMERO, REQ_STATUS, REQ_CANTIDAD, \
REQ_TOTAL, SOL_RFQ_NUMERO, SOL_HITO, SOL_ESTATUS, SOL_FECHA, SOL_SIG_HITO, SOL_SIG_HITO_ESTATUS, SOL_SIG_HITO_FECHA, ORC_NUMERO_OC, \
ORC_LINEA, ORC_SUB_LINEA, ORC_DESTINO, ORC_CANTIDAD, ORC_FECHA_RAS, ORC_FECHA_SOP, ORC_GRUPO_DE_EMBARQUE, ORC_HITO, ORC_ESTATUS, \
ORC_FECHA, ORC_SIG_HITO, ORC_SIG_HITO_ESTATUS, ORC_SIG_HITO_FECHA, TB_INDEX FROM railway.equipos_e_instrumentos;"

    QUERY_EQUIPOS_PEND = "SELECT CAT_FILA, CAT_DISCIPLINA, CAT_MATL_TYPE, CAT_TAG_NUMBER, CAT_DESCRIPCION, CAT_CWP, CAT_CWP_DESCRIPCION, \
CAT_CONTRATO, CAT_DESTINO, CAT_ESTADO, REQ_LOG, REQ_REQ_NUMERO, REQ_DESCRIPCION_SUPLEMENTO, REQ_NUMERO, REQ_STATUS, REQ_CANTIDAD, \
REQ_TOTAL, SOL_RFQ_NUMERO, SOL_HITO, SOL_ESTATUS, SOL_FECHA, SOL_SIG_HITO, SOL_SIG_HITO_ESTATUS, SOL_SIG_HITO_FECHA, ORC_NUMERO_OC, \
ORC_LINEA, ORC_SUB_LINEA, ORC_DESTINO, ORC_CANTIDAD, ORC_FECHA_RAS, ORC_FECHA_SOP, ORC_GRUPO_DE_EMBARQUE, ORC_HITO, ORC_ESTATUS, \
ORC_FECHA, ORC_SIG_HITO, ORC_SIG_HITO_ESTATUS, ORC_SIG_HITO_FECHA, TB_INDEX FROM railway.equipos_e_instrumentos \
where REQ_CANTIDAD < CAST(ORC_CANTIDAD AS UNSIGNED);"

    QUERY_EQUIPOS_COMP = "SELECT CAT_FILA, CAT_DISCIPLINA, CAT_MATL_TYPE, CAT_TAG_NUMBER, CAT_DESCRIPCION, CAT_CWP, CAT_CWP_DESCRIPCION, \
CAT_CONTRATO, CAT_DESTINO, CAT_ESTADO, REQ_LOG, REQ_REQ_NUMERO, REQ_DESCRIPCION_SUPLEMENTO, REQ_NUMERO, REQ_STATUS, REQ_CANTIDAD, \
REQ_TOTAL, SOL_RFQ_NUMERO, SOL_HITO, SOL_ESTATUS, SOL_FECHA, SOL_SIG_HITO, SOL_SIG_HITO_ESTATUS, SOL_SIG_HITO_FECHA, ORC_NUMERO_OC, \
ORC_LINEA, ORC_SUB_LINEA, ORC_DESTINO, ORC_CANTIDAD, ORC_FECHA_RAS, ORC_FECHA_SOP, ORC_GRUPO_DE_EMBARQUE, ORC_HITO, ORC_ESTATUS, \
ORC_FECHA, ORC_SIG_HITO, ORC_SIG_HITO_ESTATUS, ORC_SIG_HITO_FECHA, TB_INDEX FROM railway.equipos_e_instrumentos \
where REQ_CANTIDAD = CAST(ORC_CANTIDAD AS UNSIGNED);"

    QUERY_EQUIPO = "SELECT CAT_FILA, CAT_DISCIPLINA, CAT_MATL_TYPE, CAT_TAG_NUMBER, CAT_DESCRIPCION, CAT_CWP, CAT_CWP_DESCRIPCION, \
CAT_CONTRATO, CAT_DESTINO, CAT_ESTADO, REQ_LOG, REQ_REQ_NUMERO, REQ_DESCRIPCION_SUPLEMENTO, REQ_NUMERO, REQ_STATUS, REQ_CANTIDAD, \
REQ_TOTAL, SOL_RFQ_NUMERO, SOL_HITO, SOL_ESTATUS, SOL_FECHA, SOL_SIG_HITO, SOL_SIG_HITO_ESTATUS, SOL_SIG_HITO_FECHA, ORC_NUMERO_OC, \
ORC_LINEA, ORC_SUB_LINEA, ORC_DESTINO, ORC_CANTIDAD, ORC_FECHA_RAS, ORC_FECHA_SOP, ORC_GRUPO_DE_EMBARQUE, ORC_HITO, ORC_ESTATUS, \
ORC_FECHA, ORC_SIG_HITO, ORC_SIG_HITO_ESTATUS, ORC_SIG_HITO_FECHA, TB_INDEX FROM railway.equipos_e_instrumentos \
where TB_INDEX = (%(miid)s);"
    
    