class Querys_equipos:

    #Sentencias a la base de datos
    
    QUERY_ALL_EQUIPOS = "SELECT OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
                        CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
                        FROM amsa.Control_Perneria;"
    
    QUERY_X_SNF = "SELECT OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
                    CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
                    FROM amsa.Control_Perneria "
    
    QUERY_PENDIENTES = "SELECT OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
FROM amsa.Control_Perneria  WHERE DIFERENCIA != 0"

    QUERY_COMPLETAS = "SELECT OC, CONTRATO, GUIA, SNF, BULTO, ITEMCODE, TIPO_ELEMENTO, MARCA, MARCA2, TUNEL, DISPOSICION_FINAL, CANTIDAD_SNF, \
CANTIDAD_TERRENO, DIFERENCIA, PESO_UNITARIO, PESO_TOTAL, PROVEEDOR, PATIO, FECHA_LLEGADA, OBSERVACION, NB_ASIG_TERR \
FROM amsa.Control_Perneria  WHERE DIFERENCIA = 0"
                    
    