class Querys_perneria:

    #Sentencias a la base de datos
    
    
    QUERY_PERNERIA = "SELECT P.ID_PERNO, P.OC, P.CONTRATO, P.GUIA, P.SNF, P.BULTO, P.ITEMCODE, P.TIPO_ELEMENTO, P.MARCA, P.MARCA2, P.TUNEL, \
    P.DISPOSICION_FINAL, P.CANTIDAD_SNF, P.CANTIDAD_TERRENO, P.DIFERENCIA, P.PESO_UNITARIO, P.PESO_TOTAL, P.PROVEEDOR, P.PATIO, \
    STR_TO_DATE(P.FECHA_LLEGADA, '%d-%m-%Y') AS FECHA_LLEGADA,  \
    P.OBSERVACION, P.NB_ASIG_TERR, TP.DESCRIPCION as TIPOELEM_DESCRIPCION,  TU.DESCRIPCION as TUNEL_DESCRIPCION,  DI.DESCRIPCION as DISPO_DESCRIPCION, PR.DESCRIPCION as PROVE_DESCRIPCION, PA.DESCRIPCION as PATIO_DESCRIPCION, ROUND((CANTIDAD_TERRENO/CANTIDAD_SNF)*100, 2) AS PORCENTAJE, 0 as isEdit, false as isSelected  \
    FROM control_perneria P \
    INNER JOIN TIPO_ELEMENTO TP \
        ON P.TIPO_ELEMENTO = TP.ID_TPELEMENTO \
    INNER JOIN TUNEL TU \
        ON P.TUNEL = TU.ID_TUNEL \
    INNER JOIN disposicion DI \
        ON P.DISPOSICION_FINAL = DI.ID_DISP_FINAL  \
    INNER JOIN proveedor PR \
        ON P.PROVEEDOR = PR.ID_PROVEEDOR  \
    INNER JOIN PATIO PA \
        ON P.PATIO = PA.ID_PATIO \
    "
    
    